### ISSUE TITLE
[Feature request] Return also result of diff() from action

### ISSUE THREAD

**Issue by ddeath** [madhead/semver-utils#554]
Returning diff() result from action would allow us to build more complex validation.

For example if we want to check that version bump is strictly +1 in major | minor | patch number

**Comment by madhead** [comment]
Hej, @ddeath!

Thank you for the suggestion! Do you have an example of such `diff` function?

**Comment by madhead** [comment]
https://www.npmjs.com/package/semver-diff?

**Comment by madhead** [comment]
Hej, @ddeath!

Please, check out the `3.1.0` version with the `diff()` support.

Thanks for the suggestion!

**Comment by ddeath** [comment]
Oh thank you, that was really fast haha, I just forked this repo that I will create PR 😄  but you were faster...

I did not read the docs properly for that diff() function sadly it just returns words like `patch`, `minor`, `major` but I was expecting something more like:
```
{
    "major": 1,
    "minor": -2,
    "patch": 0
}
``` 

hehe like relative change to each version number
